"""doubly model

Revision ID: 3b10d9832d97
Revises: e5493b41734d
Create Date: 2022-11-22 10:56:36.245278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b10d9832d97'
down_revision = 'e5493b41734d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubly',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('b', sa.Float(), nullable=True),
    sa.Column('h', sa.Float(), nullable=True),
    sa.Column('cc', sa.Float(), nullable=True),
    sa.Column('dbm', sa.Float(), nullable=True),
    sa.Column('dbv', sa.Float(), nullable=True),
    sa.Column('fc', sa.Float(), nullable=True),
    sa.Column('fy', sa.Float(), nullable=True),
    sa.Column('k', sa.Float(), nullable=True),
    sa.Column('Lc', sa.Float(), nullable=True),
    sa.Column('Mu', sa.Float(), nullable=True),
    sa.Column('d', sa.Float(), nullable=True),
    sa.Column('b_check', sa.String(length=50), nullable=True),
    sa.Column('span_check', sa.String(length=50), nullable=True),
    sa.Column('B1', sa.Float(), nullable=True),
    sa.Column('pbal', sa.Float(), nullable=True),
    sa.Column('pmin', sa.Float(), nullable=True),
    sa.Column('pmax', sa.Float(), nullable=True),
    sa.Column('Φ', sa.Float(), nullable=True),
    sa.Column('Rn', sa.Float(), nullable=True),
    sa.Column('preq', sa.Float(), nullable=True),
    sa.Column('duct_check', sa.String(length=50), nullable=True),
    sa.Column('Asreq', sa.Float(), nullable=True),
    sa.Column('a', sa.Float(), nullable=True),
    sa.Column('c', sa.Float(), nullable=True),
    sa.Column('fs', sa.Float(), nullable=True),
    sa.Column('yield_check', sa.String(length=50), nullable=True),
    sa.Column('doubly_check', sa.String(length=50), nullable=True),
    sa.Column('Mn', sa.Float(), nullable=True),
    sa.Column('cd', sa.Float(), nullable=True),
    sa.Column('ad', sa.Float(), nullable=True),
    sa.Column('As1', sa.Float(), nullable=True),
    sa.Column('Mn1', sa.Float(), nullable=True),
    sa.Column('Mn2', sa.Float(), nullable=True),
    sa.Column('dp', sa.Float(), nullable=True),
    sa.Column('As2', sa.Float(), nullable=True),
    sa.Column('Asd', sa.Float(), nullable=True),
    sa.Column('Nsd', sa.Float(), nullable=True),
    sa.Column('Nsdf', sa.Float(), nullable=True),
    sa.Column('fsp', sa.Float(), nullable=True),
    sa.Column('Asp', sa.Float(), nullable=True),
    sa.Column('Nsp', sa.Float(), nullable=True),
    sa.Column('Nspf', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doubly')
    # ### end Alembic commands ###
