"""empty message

Revision ID: e5493b41734d
Revises: 931ff4f63542
Create Date: 2022-11-19 19:17:28.439908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5493b41734d'
down_revision = '931ff4f63542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('timestamp2', sa.Date(), nullable=True))
    op.create_index(op.f('ix_member_timestamp2'), 'member', ['timestamp2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_timestamp2'), table_name='member')
    op.drop_column('member', 'timestamp2')
    # ### end Alembic commands ###
